services:
  express-app:
    image: ${DOCKER_USERNAME}/express-app:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
